# Generated by Django 5.1.2 on 2024-10-11 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('period', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetAlert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trigger_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=150)),
                ('format', models.CharField(choices=[('CSV', 'CSV'), ('Excel', 'Excel')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('budget_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_tracker_app.budget')),
            ],
        ),
        migrations.AddField(
            model_name='budget',
            name='expense_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_tracker_app.expensecategory'),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('income_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_tracker_app.incomecategory')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_tracker_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('expense_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_tracker_app.expensecategory')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_tracker_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='budget',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_tracker_app.user'),
        ),
    ]
